[FIX]: deploy yml indents

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -22,36 +22,36 @@ jobs:
     name: Production
     # url: ${prod url}
 
-    steps:
-      - name: Verify Tag Exists Remotely
-        run: |
-          if git ls-remote --exit-code --tags origin "refs/tags/${{ inputs.tag }}" >/dev/null 2>&1; then
-            echo "✅ Tag '${{ inputs.tag }}' found on remote."
-          else
-            echo "❌ Error: Tag '${{ inputs.tag }}' does not exist."
-            exit 1
-          fi
+  steps:
+    - name: Verify Tag Exists Remotely
+      run: |
+        if git ls-remote --exit-code --tags origin "refs/tags/${{ inputs.tag }}" >/dev/null 2>&1; then
+          echo "✅ Tag '${{ inputs.tag }}' found on remote."
+        else
+          echo "❌ Error: Tag '${{ inputs.tag }}' does not exist."
+          exit 1
+        fi
 
-      - name: Checkout Specific Tag
-        uses: actions/checkout@v4
-        with:
-          ref: ${{ inputs.tag }}
-          fetch-depth: 1
+    - name: Checkout Specific Tag
+      uses: actions/checkout@v4
+      with:
+        ref: ${{ inputs.tag }}
+        fetch-depth: 1
 
-      - name: Setup Node.js
-        uses: actions/setup-node@v4
-        with:
-          node-version: 22
-          cache: 'npm'
+    - name: Setup Node.js
+      uses: actions/setup-node@v4
+      with:
+        node-version: 22
+        cache: 'npm'
 
-      - name: Install dependencies
-        run: npm ci
+    - name: Install dependencies
+      run: npm ci
 
-      - name: Pull Vercel Environment Information
-        run: npx vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
+    - name: Pull Vercel Environment Information
+      run: npx vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
 
-      - name: Build Project Artifacts
-        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
+    - name: Build Project Artifacts
+      run: npx vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
 
-      - name: Deploy Project Artifacts to Vercel
-        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
+    - name: Deploy Project Artifacts to Vercel
+      run: npx vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
